name: Tu Dong Commit Moi Ngay

on:
  schedule:
    - cron: '5 * * * *' # Chạy tự động vào 7h sáng mỗi ngày (giờ VN)
  workflow_dispatch: # Giúp bạn có nút để bấm chạy thủ công bất cứ lúc nào

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create random commit content
        run: |
          MESSAGES=("Update technical indicators" "Refactor smart contract code" "Add new build logs" "Check network status" "Sync with Base Mainnet")
          RANDOM_MSG=${MESSAGES[$RANDOM % ${#MESSAGES[@]}]}
          echo "$(date): $RANDOM_MSG - Project Update" >> history.txt

      - name: Commit va Push
        run: |
          git config --local user.email "trunghoai199533@gmail.com"
          git config --local user.name "bucute95"
          git add history.txt
          git commit -m "chore: update project base network 2"
          git push
